services:
  db:
    image: postgres:16
    container_name: airbnb_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airbnb_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
